- README.md
- bindings.go
- doc.go
- rabbithole_test.go
This closes #24 and closes #21.
This adds support for creating and removing Exchange-to-Exchange and Exchange-to-Queue bindings. Tests were added to cover adding and deleting bindings. When you add a binding, the response has a Location header that will contain {destination}/{propertiesKey}. It's up to the caller to grab that from the header if they need it for future operations (like Delete). 
*I also had to modify the test for "GET /connections" to work when Rabbit is hosted in a container or VM*
> Added support for declaring and deleting bindings

- nodes.go
ListNodes() failed with "json: cannot unmarshal number 7230497580 into Go value of type uint32".
> Changed node uptime in nodeinfo struct to uint64

- README.md
- bindings.go
- channels.go
- client.go
- connections.go
- exchanges.go
- misc.go
- nodes.go
- permissions.go
- policies.go
- queues.go
- users.go
- vhosts.go
I added SSL/TLS support by allowing the dev to use `http.Transport`, which allows them to throw in a `tls.Config` object to make the connection run through SSL/TLS.
> Adds Configurable SSL/TLS Support

- common.go
This fixes #60. While I could have fixed this particular problem by adding `,string` to the tag for Port in `BrokerContext`, its not clear to me whether the is a problem for all versions of Rabbitmq or just this particular one.
Let me know if there are any changes that you'd like me to make.
> Handle when rabbitmq sends a port value in a string

- CONTRIBUTING.md
- common.go
- rabbithole_test.go
This pull requests adds remaining fields: `deliver_get`, `redeliver`, `get`, `get_no_ack` to the `MessageStats` struct
```json
"MessageStats": {
"publish": 55194,
"publish_details": {
"rate": 271.2
},
"deliver_get": 100,
"deliver_get_details": {
"rate": 0
},
"redeliver": 0,
"redeliver_details": {
"rate": 0
},
"get": 0,
"get_details": {
"rate": 0
},
"get_no_ack": 100,
"get_no_ack_details": {
"rate": 0
}
}
```
> Add remaining attributes to MessageStats struct

- common.go
- rabbithole_test.go
Exposing fields previously ignored from API response, these are needed for metrics.
> Added Deliver and DeliverNoAck fields to MessageStats struct

- queues.go
Currently the ConsumerUtilisation is available on the API response from `/queues`, but is not returned by rabbit-hole. This adds that to the QueueInfo object.
The `consumer_utilisation` property in the response from RabbitMQ can be null when there are no consumers, or there are no messages. This gets marshalled to 0, which is appropriate and matches the behaviour of the RabbitMQ management GUI.
> Add ConsumerUtilisation to QueueInfo

- bin/ci/before_build.sh
- rabbithole_test.go
The new mgmt plugin developed in https://github.com/rabbitmq/rabbitmq-management/issues/236 publishes the stats in batches using the smallest sample retention policy interval available.
This patch sets the interval to 1s and add a minimal wait for it on the tests. Tests will be slower, but should run in less than 50s.
> Wait for stats to be published in new management plugin

- common.go
'int' is between operating systems.
OSX - int64
Windows - int
force to int64 to prevent JSON parsing issues.
testing this is overkill so I skipped that.  If you want a test, I can write one, but it passes on my dev machine due to int appearing as int64 on my dev machine.
> concrete stat types for MessageStats

- README.md
- bin/ci/before_build.bat
- bin/ci/before_build.sh
- rabbithole_test.go
- shovels.go
Adds supports for shovels
- ListShovels
- ListShovelsIn
- GetShovel
- DeclareShovel
- DeleteShovel
Also enabled 'rabbitmq_shovel' and 'rabbitmq_shovel_management' plugins in before_build as well as created a .bat equivalent for running tests on Windows.
As far as tests are concerned, I just have the one that creates a shovel, checks the config, then deletes it. Are there other tests you would like to see?
Fixes https://github.com/michaelklishin/rabbit-hole/issues/91
As a side note, I get an error with the second eval.
```
call %RABBITHOLE_RABBITMQCTL% eval "supervisor2:terminate_child(rabbit_mgmt_agent_sup_sup, rabbit_mgmt_agent_sup), application:set_env(rabbitmq_management_agent, sample_retention_policies, [{global, [{605, 1}]}, {basic, [{605, 1}]}, {detailed, [{10, 1}]}]), …
```
> Adds Shovel support

- client.go
add Client HTTP timeout
\+ simplify the code
> add Client HTTP timeout

- README.md
- rabbithole_test.go
- users.go
According to the [RabbitMQ Management HTTP API documentation](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_9/priv/www/api/index.html), calling `PUT /api/users/{name}` with an empty password_hash field disables a user's password, just like the `rabbitmqctl clear_password {username}` command.
I implemented this feature with the new `PutUserWithoutPassword` method.
> Support PUT /api/users/{name} with empty password_hash

- README.md
- bin/ci/before_build.sh
- cluster.go
- doc.go
- rabbithole_test.go
Hi,
thank you for this great package, it's very useful for my project. Since it requires to programmaticaly rename the cluster, I added SetClusterName()/GetClusterName() functions.
Thanks.
regards,
> Add support to manipulate cluster name

- nodes.go
Added proc_used and proc_total to NodeInfo struct for grabbing erlang process usage.
> proc_used/proc_total

- exchanges.go
- queues.go
- users.go
As indicated https://rawcdn.githack.com/rabbitmq/rabbitmq-management/v3.7.7/priv/www/api/index.html when creating a user it is possible as well to send the password hash.
I've modified UserSettings to have that option.
> Be able to specify password_hash when creating a new user

- README.md
- client.go
https://golang.org/pkg/net/http/#RoundTripper
This will allow anyone to pass through custom transport implementations, such as logging transport we use over in Terraform:
https://github.com/hashicorp/terraform/blob/master/helper/logging/transport.go
`*http.Transport` implements this interface so this should not break anything.
I tried running tests via `make test` but they mostly fail (on master) for me. It may be just different environment, I don't know - I hope my changes didn't break anything. 🤞
> Change *http.Transport to http.RoundTripper

- bindings.go
- channels.go
- permissions.go
- policies.go
- topic_permissions.go
- users.go
- vhosts.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- .travis.yml
- README.md
Add Golang v1.12, drop v1.9 & v1.10. Module support was introduced in
v1.11: https://blog.golang.org/using-go-modules
Related to #128
> Fix go module support in Travis

- queues.go
- rabbithole_test.go
Changes the JSON tag for `QueueInfo.Status` field from `status` to `state`. 
Addresses issue presented here: https://github.com/michaelklishin/rabbit-hole/issues/134
> Fix QueueInfo.Status json tag

- exchanges.go
Hi Michael,
Thank you very much for the friendly go library to get various details from RabbitMQ Management.
While I was testing the library, I found that the function "rmqc.GetExchange" was not retrieving the "PublinIn, PublishOut" message stats of a exchange, Hence I have included the "PublishStats" to "struct DetailedExchangeInfo" after which I am able to retrieve the Publish IN/OUT rates as well as Count.
Sincerely,
Rajendra N Acharya
Below is the test execution results after my changes.
```
06/10/2019@11:15:38 exchange-publish-stats: /home/raachary/github/login/rabbit-hole
raachary@ubuntu> make
go test -race -v
=== RUN   TestRabbitHole
Running Suite: Rabbithole Suite
===============================
Random Seed: 1560145547
Will run 66 of 66 specs
•
------------------------------
• …
```
> support retrieving the exchange publishIn/publishOut stats

- bindings.go
- rabbithole_test.go
I discovered that `ListQueueBindingsBetween` would return no error and an empty slice when given a `url.PathEscape`-d queue name.
Now that I'm writing this my test modification is probably not right. I'll see how Travis goes then probably add some `%XY` chars.
Note: the method just above may need that same `PathEscape`.
Also, it's a long long time since go1.8, maybe we could rely on `"net/url"`'s definition of `PathEscape` now?
I can do this in a follow up PR if you want.
> PathEscape queue name in ListQueueBindingsBetween

- consumers.go
- rabbithole_test.go
This pull request add support for:
- /api/consumers
- /api/consumers/vhost
I added some tests but I'm not that familiars with gomega, so please let me know of anything seems wrong to you.
All the tests are passing.
> Add /api/consumers support

- connections.go
From RabbitMQ 3.7 the property "connected_at" is also available on a client connection.
> Added ConnectedAt property to ConnectionInfo

- doc.go
- rabbithole_test.go
- topic_permissions.go
It can be helpful to delete individual topic permissions as well as clearing all of them for a given user.
> Enable deleting a single exchange's topic permissions

- client.go
I just noticed that #145 introduces sefgaults due to nil pointer dereference on HTTP Client errors (e.g., when there's a DNS lookup problem, the server address/port is wrong etc etc). I think we should check `err` before trying to access `resp` which, obviously, can be nil.
> Fix Nil Pointer Dereference on HTTP Client errors

- README.md
- bin/ci/before_build.bat
- bin/ci/before_build.sh
- doc.go
- federation.go
- rabbithole_test.go
- runtime_parameters.go
* Adds additional client methods to allow reading of federation upstream parameters.
* Adds tests for all existing and new federation methods.
* To add federation support to the [terraform-provider-rabbitmq](https://www.terraform.io/docs/providers/rabbitmq/index.html) terraform provider, we need to be able to read federation upstream resources via the API. I'm working on this now but need these changes before I can continue.
Some notes from working on this PR.
To support the new read methods, I added additional fields to `FederationUpstream` and introduced a `FederationDefinitionDTO` type. This is an exact copy of the existing shovel implementation, which makes sense, because they are more or less the same thing.
The only required field for a federation upstream definition is `Uri`. …
> API for runtime parameters, e.g. for configuring federation upstream components.

- federation.go
- rabbithole_test.go
- runtime_parameters.go
This is a very minor follow-up to https://github.com/michaelklishin/rabbit-hole/pull/150.
* Eliminates possibility (unlikely) of panic in `paramToUpstream` when parameter map is nil.
* Uses consistent format when initializing `RuntimeParameter` structs.
Thanks for all your help with these recent pull requests. I look forward to a new release soon.
> Check RuntimeParameter value before creating FederationUpstream.

- federation.go
How to deal with default values, especially for federation definition attributes like `expires` and `message-ttl`?
This is a follow up to a question I buried in the Federation Runtime Parameters [PR](https://github.com/michaelklishin/rabbit-hole/pull/150).
Turns out, that the go zero value of `0` for `expires` (`int` type) throws an error when the federation link is created. The [docs](https://www.rabbitmq.com/ttl.html#queue-ttl) state that it must be a positive integer. This is not captured by any current tests, since it only happens when you also create a policy that matches a federation upstream and then view the status of the link that is created.
I suspected this would become an issue but it only came to light when doing a complete end-to-end test using the …
> Exclude expires field from federation definition when value is zero.

- federation_links.go
- rabbithole_test.go
This is a follow-up to https://github.com/michaelklishin/rabbit-hole/pull/154
New API calls:
* `GET /api/federation-links`
* `GET /api/federation-links/{vhost}`
> Added federation-links endpoints

- README.md
- rabbithole_test.go
- shovels.go
Hello,
please consider this pull request which adds the rest of the possible parameters to configure shovels in RMQ. My main use case for this is to be able to use AMQP 1.0 destinations/sources for connections with Azure Event Hub.
thx & best regards,
Andreas
> Add missing Parameters for Shovels

- rabbithole_test.go
- shovels.go
Delete-after can be a string (eg. "never") or an integer. RabbitMQ does
not accept string-formatted integers ("42") so this PR changes the type
of the `DeleteAfter` field and adds a custom marshaler/unmarshaler
to handle both cases. As you can see in the tests, this may be a
breaking change - since values of different types cannot be equal in Go,
when comparing `DeleteAfter` with a string, you now need to convert one of the
values. However, most operations should work without code changes.
Fixes #149
> Add support for numeric delete-after values

- runtime_parameters.go
Hello,
Nice library! thanks for making it open source. I tried to find a way to get whole rabbitmq configuration but couldn't find it.
Idea here is to get full config from rabbitmq runtime. Eventually this could be used along with terraform to eventually import/manage it.
> Basic support for definition export

- ChangeLog.md
- README.md
- rabbithole_test.go
- shovels.go
This is a 3.8-specific API endpoint feature but we still
support deserialization of 3.7 responses.
Closes #103, #172.
> Require source and dest URIs in ShovelDefinition to be collections

- federation.go
The following parameters are optional in the RabbitMQ API and may be absent in the request body. The API treats the zero-values (an empty string, for example) differently than the absence of such value. This causes the created configuration to be incorrect in some cases.
My particular use-case was to create a federation upstream without the defined exchange or queue name. However, the request generated by rabbit-hole sent those parameters as empty strings, which caused the upstream client to connect to a queue with the name `''` (queue name is mandatory, so such queue cannot exist anyway). Instead, I wanted to get the default behaviour in which any downstream queue would be federated with an upstream queue with the same name.
> Optional parameters of FederationDefinition are now marked with `omitempty` to prevent zero values from being sent to the API.

- README.md
- doc.go
- global_parameters.go
- rabbithole_test.go
- runtime_parameters.go
Adding functions to manage global parameters:
- `ListGlobalParameters()`
- `GetGlobalParameter()`
- `PutGlobalParameter()`
- `DeleteGlobalParameter()`
Will be used in topology operator to set global parameter`schema_replication_upstream_endpoints` for schema replication (currently done by `rabbitmqctl set_schema_replication_upstream_endpoints`).
> Add support for global parameters 🐰

- bindings.go
- queues.go
- rabbithole_test.go
- shovels.go
- topic_permissions.go
- unit_test.go
- users.go
- vhosts.go
**Summary**
At the moment, setting `QueueSettings.Type` when calling `DeclareQueue` does not do anything. This change sets queue argument `x-queue-type` to the value of`QueueSettings.Type` (if present). Took inspiration from: https://github.com/rabbitmq/rabbitmq-management/pull/762/files
Some small refactoring on typos and redundant type conversion. 
Thanks @mkuratczyk for looking at this together with me 😄
> Set queue type in queue argument if it's set in QueueSettings

- federation.go
- rabbithole_test.go
Closes: #192 
- Refactor FederationDefinition.Uri to []string to work with multiple uris.
- Stopping using `paramToUpstream` and use `executeAndParseRequest` directly, because`GetRuntimeParameter` or `ListRuntimeParameter` returns uri as `interface{}`which needs to be converted to `[]string` in a loop
> Refactor FederationDefinition.Uri to []string

- ChangeLog.md
- common.go
- federation.go
- rabbithole_test.go
- shovels.go
- unit_test.go
née ShovelURISet, now renamed
A follow-up to #193.
> Make both Shovel and Federation upstream URI use URISet

- nodes.go
- queues.go
I am in a SRE team. We are running rabbitmq 3.8.5 in production and find it may be useful to add more fields of metrics for NodeInfo and QueueInfo, because we could know more about running state for rabbitmq instance
> add more fields of metrics in NodeInfo and QueueInfo

- rabbithole_test.go
- vhost_limits.go
This pull request adds support to set the max-connection limit for a specified vhost (see REST API: /api/vhost-limits)
> Add vhost-limits API

- README.md
The API is available, the README is missing the examples to use the policy endpoints.
> Update README to include example to manage policies

- bindings.go
- definitions.go
- exchanges.go
- queues.go
- rabbithole_test.go
Exported definitions should not include stats and many empty fields.
> Avoid exporting stats and empty fields

- ChangeLog.md
- rabbithole_test.go
- user_limits.go
- vhost_limits.go
This PR addresses #216 and adds support for user limits feature which was added in RMQ 3.8.10.
It also adds functions to query vhost and user limits for all vhosts and users respectively.
> Add support for user limits

- CONTRIBUTING.md
- bin/ci/before_build.bat
- bin/ci/before_build.sh
- federation_links.go
- go.mod
- go.sum
- rabbithole_test.go
It does what our event propagation sleeps do [but better](https://onsi.github.io/gomega/#eventually).
This reduces full suite runtime from about 120s to about 22s-24s (a reduction of some 80%!)
> Switch to Gomega's Eventually matcher

- Makefile
> Bump rabbitmq version used in tests to 3.10.

- CONTRIBUTING.md
- rabbithole_suite_test.go
Removes need to set an environment variable to run tests by setting the default timeout within the test suite.
> Set default async test timeout to 5s.

- .github/workflows/tests.yml
v1/v2 actions are deprecated due to outdated NodeJS version.
> Update checkout and setup-go actions to v3.

- bindings.go
`info.DestinationType[0]` panics if DestinationType is empty
```
github.com/michaelklishin/rabbit-hole/v2.(*Client).DeleteBinding(0x0?, {0x14b24d8?, 0x0?}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
/Users/clyu/workspace/rabbit-hole/bindings.go:218 +0x2ce
github.com/michaelklishin/rabbit-hole/v2.glob..func2.49.1()
/Users/clyu/workspace/rabbit-hole/rabbithole_test.go:1795 +0x65
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc00068a460?)
/Users/clyu/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113 +0xb1
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0x0?)
/Users/clyu/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64 +0x125
github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0x1095560?) …
```
> Avoid out of range panic when destination type is not set

- shovels.go
dest-publish-properties is expecting a map but was getting a string.
> For Shovel changed dest-publish-properties to map

- rabbithole_test.go
- vhosts.go
Fixes #258, depends on https://github.com/rabbitmq/rabbitmq-server/pull/7739 to ship in `3.11.12`.
> Support default queue type for vhost.

- bindings.go
- doc.go
- queues.go
- rabbithole_suite_test.go
- rabbithole_test.go
- shovels.go
Related to #262
* change `dest-application-properties` and `dest-properties` to maps from strings.
See: https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_shovel/src/rabbit_shovel_parameters.erl#L156
https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_shovel/src/rabbit_shovel_parameters.erl#L172.
* add shovel parameters that are missing from rabbit-hole and test: `src-queue-args`, `src-consumer-args`, `dest-application-properties` and `dest-message-annotations`. `add-timestamp-header` and `publish-properties` are **not added** since the preferred parameters `dest-add-timestamp-header` and `dest-publish-properties` are already there.
When we release the next major and drop support for older RMQ, we can remove `add-forward-headers`, `delete-after`, and …
> Shovel properties

- bin/ci/before_build.sh
- connections.go
- rabbithole_test.go
https://github.com/rabbitmq/rabbitmq-server/pull/8483, https://github.com/rabbitmq/rabbitmq-server/pull/5319.
Currently skipped, as they will fail on all GA releases
available right now. They do pass against RabbitMQ main and 3.12, 3.11
release branches with a backport.
> Add tests for rabbitmq/rabbitmq-server#8482

- definitions.go
- rabbithole_test.go
Correspond to `POST /api/definitions/vhost`.
Basically similar to `UploadDefinitions()` but with specifying the `vhost`.
> Add UploadVhostDefinitions()

- Makefile
Fixes test failure when using `make docker.rabbitmq` to run `make test`
#261 introduced `default_queue_type` in version `3.10` the key is `defaultqueuetype`.
> fix: bump rabbitmq version in docker.rabbitmq make target

- common.go
- consumers.go
- nodes.go
- queues.go
- unit_test.go
This fixes #279.
There's discussion here as to whether all ports should be able to be `"undefined"`.
Or whether it should be separate for the ones known to be undefinable.
~I also got a test failure but got the same failure on main, haven't had a chance to look into it yet.~ #281
> fix: handle undefined ports

- queues.go
- unit_test.go
Because of https://github.com/rabbitmq/rabbitmq-server/issues/2684, in all RabbitMQ versions until 3.11.8, the
`.consumer_details.channel_details` attribute for a queue could be sent as an empty array (`[]`) instead an empty object (`{}`).
This PR provides a fix to that by customizing the json serializarion of ChannelDetails.
> Fixes issue when serializing ChannelDetails as an empty array

- common.go
`exchange.auto_delete` should not be `undefined` -> now defaults to `false` when it's string `"undefined"`, not `true`.
* by default `auto_delete` is `false`
* when `undefined`, it's more likely to behave like `false`
Please see the details / origin of this change in #309 .
I could not find any explanation for the changes in #207 .
**Why?**
_Sometimes_ there are issues with deploying exchanges using topology-operator. Unfortunately, it's a bit hard to reproduce, so I did not find the real problem yet. The exchanges are unchanged, and all set to `auto_delete: false` when being created, but the diff still says that `auto_delete` changed:
---
This is a draft, and I'm not sure how to test this, since I can only un-marshall the JSON, but setting up an exchange with `undefined` would require to …
> refs #309, unmarshalling `AutoDelete: "undefined"` to `false` not `true`

- connections.go
- go.mod
- rabbithole_test.go
In my rabbitmq production cluster, there are 8000+ connections. I find that use /api/connections without pagination to get all connection info always response timeout.
Hope that we would request /api/connections with pagination support
> Add pagination support for /api/connections

- go.mod
The repo was tagged as 3.0.0, however, the module directive was not
updated. This makes impossible to `go get` the new major version. This
commit updates the Go module directive to match the new major version.
> Update module version to v3

- go.mod
After merging this, simply tag (do not create a release) with 3.1.1.
After ~1m, run `go get github.com/michaelklishin/rabbit-hole/v3`, you should observe that it gets
version 3.1.0. Further validate by running:
```
go list -m -versions github.com/michaelklishin/rabbit-hole/v3
```
The current output is `github.com/michaelklishin/rabbit-hole/v3 v3.0.0 v3.1.0`. After tagging a version with the retraction,
it should print only 3.1.0.
> Update go.mod to publish a retract version

- federation.go
- rabbithole_test.go
Enhancing `FederationDefinition` with support for:
- `QueueType`
- `ResourceCleanupMode` 
https://www.rabbitmq.com/docs/federation-reference#applying-to-federated-exchanges-only
> Add support for QueueType and ResourceCleanupMode in FederationDefinition
