README.md
doc.go

Just noticed this when calling these.

Fixed some errors in the docs for PutVhost and UpdatePermissionsIn

---

rabbithole_test.go

Catches the initial issue that I had with #63.

Add test cases for unmarshalling port values

---

client.go

According to go docs (https://golang.org/src/net/http/response.go?s=1408:1586#L19), unless response.Body is read to completion AND closed, default http.client’s transport will not reuse keep-alive connections.
Small change to always close response body and when isNotFound is true, read and discard the response body.

Fix client.go to re-use keep-alive connections

---

client.go
doc.go
queues.go
rabbithole_suite_test.go
rabbithole_test.go
vhosts.go

I formatted this with gofmt as a standalone push so it doesn't end up getting formatted as part of some real change. Use of gofmt is a widely accepted ([and officially recommended](https://golang.org/doc/effective_go.html#formatting)) part of the Go experience.

formatted everything with gofmt -s -w .

---

ChangeLog.md

**M**: [ChangeLog.md](https://github.com/gonkulator/rabbit-hole/blob/master/ChangeLog.md)
- I linked the contributors listed in the document.

Added A Markup Link

---

rabbithole_test.go

Solves the race condition in the test suite discovered in https://github.com/rabbitmq/rabbitmq-management/pull/101

Wait until previous connections are closed

---

bin/ci/before_build.sh

Part of https://github.com/rabbitmq/rabbitmq-management/issues/236

Use agent supervisor to restart DB

---

client.go
common.go
queues.go
rabbithole_test.go

Allow fetching queues with query GET arguments

---

client.go
error.go
rabbithole_test.go

Fixes #87.
@michaelklishin @jackmanlabs

Fix #87: non 2xx errors return error code

---

common.go

Insert properties to grab ack informations.

Insert properties the ack on messagestats struct

---

doc.go
rabbithole_test.go
topic_permissions.go

As requested in michaelklishin/rabbit-hole#111
RabbitMQ >= 3.7.0 added a new API endpoint.

Support topic-permissions API

---

README.md
queues.go
rabbithole_test.go

Added support for queue sync/cancel_sync actions
- /api/queues/vhost/name/actions

Implemented methods for SyncQueue and CancelSyncQueue

---

client.go

Addresses: https://github.com/michaelklishin/rabbit-hole/issues/112

return error if credentials are invalid

---

vhosts.go

This pull request adds support for vhost cluster status #105

Add "cluster_state" to VhostInfo

---

rabbithole_test.go

https://github.com/michaelklishin/rabbit-hole/pull/162 added support for
vhost cluster state. This PR just adds that field to the tests.
Closes #105

Test vhost cluster state

---

queues.go
rabbithole_test.go

Allows for more careful deletes via if-empty and if-unused.

Add support for queue delete options.

---

misc.go
rabbithole_test.go
users.go

Adapting to the HTTP API change coming in https://github.com/rabbitmq/rabbitmq-server/issues/2667. Note that we aim to support both this and older API response formats.
Pair: @mkuratczyk.

Make user tags a list

---

rabbithole_test.go
vhosts.go

Add possibility to set Description and Tags in vhost creation.

Add vhost description and tags

---

operator_policies.go
rabbithole_test.go

Implements [operator policies](https://www.rabbitmq.com/parameters.html#operator-policies) (#188)

Support operator policy

---

definitions.go
rabbithole_test.go

Corresponds to /api/definitions/vhost

Add ListVhostDefinitions

---

queues.go

omitempty (and for structs - use pointers to avoid nulls)

More data to skip on retrieval

---

rabbithole_test.go
vhosts_connections.go

Added a method to query for active vhost connections

list vhost connections

---

queues.go
rabbithole_test.go

Resolves #212
I followed the format of other calls, but I was unsure if I should put them after their respective non-vhost calls, or all after the ListIn. I chose the former.

Implement vhosts equivalents for [Paged]ListQueuesWithParameters

---

federation.go

Do not set messageTTL when omitted.

---

nodes.go

Remove stats that are being removed as part of removing FHC fd tracking in https://github.com/rabbitmq/rabbitmq-server/pull/11436

Remove sockets_used/total stats

---

Makefile
deprecated_features.go
deprecated_features_test.go
rabbithole_test.go

- **Add support for deprecated features endpoint**
- **Make tests more resilient to slow emit stats**

Add support for deprecated features endpoint
